import json

class StudioArranger:
    def __init__(self, config_path="config.json"):
        with open(config_path, "r") as f:
            self.config = json.load(f)
        
    def generate_mixer_layout_script(self) -> str:
        """
        Generates a native FL Studio script that automatically names, 
        colors, and structures the mixer board into pristine stems.
        """
        script_content = """# name=EPIC-STUDIO'S Console Organizer
# Auto-generated by Structural Arranger Module

import mixer
import app

def OnInit():
    print("[EPIC-STUDIO'S] Aligning mixer console to major label stem standards...")
    
    # Industry Color Palette Constants (Hex converted to FL Integer Format)
    COLOR_ORCHESTRAL = 0x8E75B2  # Deep Purple
    COLOR_PERCUSSION = 0x3B82F6  # Blue
    COLOR_BASS       = 0xEF4444  # Red
    COLOR_FX         = 0x10B981  # Green
    COLOR_MASTER     = 0xF59E0B  # Amber

    # Define Stem Bus Index Assignments
    stems = {
        1: {"name": "BUS - STRINGS/WOOD", "color": COLOR_ORCHESTRAL},
        2: {"name": "BUS - BRASS/SYNTH",  "color": COLOR_ORCHESTRAL},
        3: {"name": "BUS - PERCUSSION",   "color": COLOR_PERCUSSION},
        4: {"name": "BUS - SUB BASS",     "color": COLOR_BASS},
        5: {"name": "BUS - FX/CINEMATIC", "color": COLOR_FX}
    }

    # Initialize and lock the stem busses
    for track_idx, data in stems.items():
        mixer.setTrackName(track_idx, data["name"])
        mixer.setTrackColor(track_idx, data["color"])
        # Route stem tracks directly to the Master Bus (Track 0)
        mixer.routeTo(track_idx, 0, 1.0)
        
    # Configure 32-bit Headroom Safeguards across sub-channels
    for i in range(1, 6):
        mixer.setTrackVolume(i, 0.78) # Set to default professional unity gain (-3dB headroom)

    print("[EPIC-STUDIO'S] Mixer matrix structured successfully. Headroom verified.")
"""
        return script_content

if __name__ == "__main__":
    arranger = StudioArranger()
    print("[EPIC-STUDIO'S] Compiling Native Console Script...")
    with open("hardware/device_EpicConsole.py", "w") as f:
        f.write(arranger.generate_mixer_layout_script())
    print("Script written to hardware/device_EpicConsole.py")
